// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyc5HpF168XH7xcz9EZa5vWs9-kL6bPIk',
    appId: '1:1039363994934:web:7a1d7c9998103215646f97',
    messagingSenderId: '1039363994934',
    projectId: 'e-commerce-app-88ab6',
    authDomain: 'e-commerce-app-88ab6.firebaseapp.com',
    storageBucket: 'e-commerce-app-88ab6.firebasestorage.app',
    measurementId: 'G-378LWJ3VV0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn8QAidCtEftazu1CsJypT4uYKpAs_kaQ',
    appId: '1:1039363994934:android:7ef45ba97330daec646f97',
    messagingSenderId: '1039363994934',
    projectId: 'e-commerce-app-88ab6',
    storageBucket: 'e-commerce-app-88ab6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsWd6pchXMCJZdsCyxi-fMiRqSylqe6AA',
    appId: '1:1039363994934:ios:6ac084ef17b0ea1b646f97',
    messagingSenderId: '1039363994934',
    projectId: 'e-commerce-app-88ab6',
    storageBucket: 'e-commerce-app-88ab6.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsWd6pchXMCJZdsCyxi-fMiRqSylqe6AA',
    appId: '1:1039363994934:ios:6ac084ef17b0ea1b646f97',
    messagingSenderId: '1039363994934',
    projectId: 'e-commerce-app-88ab6',
    storageBucket: 'e-commerce-app-88ab6.firebasestorage.app',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyc5HpF168XH7xcz9EZa5vWs9-kL6bPIk',
    appId: '1:1039363994934:web:a42f0b6196d929a3646f97',
    messagingSenderId: '1039363994934',
    projectId: 'e-commerce-app-88ab6',
    authDomain: 'e-commerce-app-88ab6.firebaseapp.com',
    storageBucket: 'e-commerce-app-88ab6.firebasestorage.app',
    measurementId: 'G-1CZTW76R3W',
  );
}
